=== Cardiac-Disease-detection-using-ar-vr/INTERN-2/schemas/base_score.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Cardiac Base Score",
  "type": "object",

  "required": [
    "patient_id",
    "prediction",
    "echo",
    "ecg",
    "explainability",
    "metadata"
  ],

  "properties": {

    "patient_id": {
      "type": "string"
    },

    "prediction": {

      "type": "object",

      "required": [
        "base_score",
        "class",
        "class_label",
        "softmax"
      ],

      "properties": {

        "base_score": {
          "type": "number"
        },

        "class": {
          "type": "integer"
        },

        "class_label": {
          "type": "string"
        },

        "softmax": {

          "type": "array",

          "items": {
            "type": "number"
          },

          "minItems":3,
          "maxItems":3
        }

      }

    },

    "echo": {

      "type":"object",

      "required":[
        "predicted_ef",
        "ground_truth_ef"
      ],

      "properties":{

        "predicted_ef":{
          "type":"number"
        },

        "ground_truth_ef":{
          "type":"number"
        }

      }

    },

    "ecg":{

      "type":"object",

      "required":[
        "representation",
        "top_embedding_dimension",
        "importance"
      ],

      "properties":{

        "representation":{
          "type":"string"
        },

        "top_embedding_dimension":{
          "type":"integer"
        },

        "importance":{
          "type":"number"
        }

      }

    },

    "explainability":{

      "type":"object",

      "required":[
        "gradcam_ed",
        "gradcam_es"
      ],

      "properties":{

        "gradcam_ed":{
          "type":"string"
        },

        "gradcam_es":{
          "type":"string"
        }

      }

    },

    "metadata":{

      "type":"object",

      "required":[
        "fusion_type",
        "echo_dataset",
        "ecg_dataset",
        "intern"
      ],

      "properties":{

        "fusion_type":{
          "type":"string"
        },

        "echo_dataset":{
          "type":"string"
        },

        "ecg_dataset":{
          "type":"string"
        },

        "intern":{
          "type":"string"
        }

      }

    }

  }

}

=== Cardiac-Disease-detection-using-ar-vr/INTERN-2/interim/base_scores/0X1A030EFDD45062FA_base.json
{
    "patient_id": "0X1A030EFDD45062FA",
    "prediction": {
        "base_score": 0.4236051142215729,
        "class": 1,
        "class_label": "Mild",
        "softmax": [
            0.34347426891326904,
            0.4236051142215729,
            0.23292066156864166
        ]
    },
    "echo": {
        "predicted_ef": 50.67525863647461,
        "ground_truth_ef": 44.4856997
    },
    "ecg": {
        "representation": "512-dimensional embedding",
        "top_embedding_dimension": 497,
        "importance": 3.963246344240615
    },
    "explainability": {
        "gradcam_ed": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X1A030EFDD45062FA_ed.png",
        "gradcam_es": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X1A030EFDD45062FA_es.png"
    },
    "metadata": {
        "fusion_type": "Late Fusion",
        "echo_dataset": "EchoNet-Dynamic",
        "ecg_dataset": "PTB-XL / MIT-BIH",
        "intern": "Intern 2"
    }
}

=== Cardiac-Disease-detection-using-ar-vr/INTERN-2/interim/base_scores/0X23F7E889AEC65CC6_base.json
{
    "patient_id": "0X23F7E889AEC65CC6",
    "prediction": {
        "base_score": 0.5145400166511536,
        "class": 0,
        "class_label": "Normal",
        "softmax": [
            0.5145400166511536,
            0.26251763105392456,
            0.2229423224925995
        ]
    },
    "echo": {
        "predicted_ef": 59.465084075927734,
        "ground_truth_ef": 60.49061501
    },
    "ecg": {
        "representation": "512-dimensional embedding",
        "top_embedding_dimension": 497,
        "importance": 3.963246344240615
    },
    "explainability": {
        "gradcam_ed": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X23F7E889AEC65CC6_ed.png",
        "gradcam_es": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X23F7E889AEC65CC6_es.png"
    },
    "metadata": {
        "fusion_type": "Late Fusion",
        "echo_dataset": "EchoNet-Dynamic",
        "ecg_dataset": "PTB-XL / MIT-BIH",
        "intern": "Intern 2"
    }
}

=== Cardiac-Disease-detection-using-ar-vr/INTERN-2/interim/base_scores/0X48AEC7223D38243F_base.json
{
    "patient_id": "0X48AEC7223D38243F",
    "prediction": {
        "base_score": 0.5001778602600098,
        "class": 1,
        "class_label": "Mild",
        "softmax": [
            0.26888343691825867,
            0.5001778602600098,
            0.23093865811824799
        ]
    },
    "echo": {
        "predicted_ef": 46.07900619506836,
        "ground_truth_ef": 30.36282215
    },
    "ecg": {
        "representation": "512-dimensional embedding",
        "top_embedding_dimension": 202,
        "importance": 0.03193804368604712
    },
    "explainability": {
        "gradcam_ed": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X48AEC7223D38243F_ed.png",
        "gradcam_es": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X48AEC7223D38243F_es.png"
    },
    "metadata": {
        "fusion_type": "Late Fusion",
        "echo_dataset": "EchoNet-Dynamic",
        "ecg_dataset": "PTB-XL / MIT-BIH",
        "intern": "Intern 2"
    }
}

=== Cardiac-Disease-detection-using-ar-vr/INTERN-2/interim/base_scores/0X39430B9C27CAE73E_base.json
{
    "patient_id": "0X39430B9C27CAE73E",
    "prediction": {
        "base_score": 0.5145467519760132,
        "class": 0,
        "class_label": "Normal",
        "softmax": [
            0.5145467519760132,
            0.2625119388103485,
            0.2229413390159607
        ]
    },
    "echo": {
        "predicted_ef": 59.46562576293945,
        "ground_truth_ef": 57.03791036
    },
    "ecg": {
        "representation": "512-dimensional embedding",
        "top_embedding_dimension": 497,
        "importance": 3.963246344240615
    },
    "explainability": {
        "gradcam_ed": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X39430B9C27CAE73E_ed.png",
        "gradcam_es": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X39430B9C27CAE73E_es.png"
    },
    "metadata": {
        "fusion_type": "Late Fusion",
        "echo_dataset": "EchoNet-Dynamic",
        "ecg_dataset": "PTB-XL / MIT-BIH",
        "intern": "Intern 2"
    }
}

=== Cardiac-Disease-detection-using-ar-vr/INTERN-2/interim/base_scores/0X175303C2D48B91CA_base.json
{
    "patient_id": "0X175303C2D48B91CA",
    "prediction": {
        "base_score": 0.44584178924560547,
        "class": 0,
        "class_label": "Normal",
        "softmax": [
            0.44584178924560547,
            0.3235800266265869,
            0.23057821393013
        ]
    },
    "echo": {
        "predicted_ef": 55.33677673339844,
        "ground_truth_ef": 57.60717332
    },
    "ecg": {
        "representation": "512-dimensional embedding",
        "top_embedding_dimension": 497,
        "importance": 3.963246344240615
    },
    "explainability": {
        "gradcam_ed": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X175303C2D48B91CA_ed.png",
        "gradcam_es": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X175303C2D48B91CA_es.png"
    },
    "metadata": {
        "fusion_type": "Late Fusion",
        "echo_dataset": "EchoNet-Dynamic",
        "ecg_dataset": "PTB-XL / MIT-BIH",
        "intern": "Intern 2"
    }
}

=== Cardiac-Disease-detection-using-ar-vr/INTERN-2/interim/base_scores/0X2C18E8C665E9D9A3_base.json
{
    "patient_id": "0X2C18E8C665E9D9A3",
    "prediction": {
        "base_score": 0.5487416386604309,
        "class": 0,
        "class_label": "Normal",
        "softmax": [
            0.5487416386604309,
            0.23394016921520233,
            0.21731817722320557
        ]
    },
    "echo": {
        "predicted_ef": 63.29887390136719,
        "ground_truth_ef": 67.96295296
    },
    "ecg": {
        "representation": "512-dimensional embedding",
        "top_embedding_dimension": 202,
        "importance": 0.03193804368604712
    },
    "explainability": {
        "gradcam_ed": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X2C18E8C665E9D9A3_ed.png",
        "gradcam_es": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X2C18E8C665E9D9A3_es.png"
    },
    "metadata": {
        "fusion_type": "Late Fusion",
        "echo_dataset": "EchoNet-Dynamic",
        "ecg_dataset": "PTB-XL / MIT-BIH",
        "intern": "Intern 2"
    }
}

=== Cardiac-Disease-detection-using-ar-vr/INTERN-2/interim/base_scores/0X4A0B8B249A18FC1C_base.json
{
    "patient_id": "0X4A0B8B249A18FC1C",
    "prediction": {
        "base_score": 0.47153177857398987,
        "class": 1,
        "class_label": "Mild",
        "softmax": [
            0.29732030630111694,
            0.47153177857398987,
            0.23114795982837677
        ]
    },
    "echo": {
        "predicted_ef": 48.18379211425781,
        "ground_truth_ef": 54.85496473
    },
    "ecg": {
        "representation": "512-dimensional embedding",
        "top_embedding_dimension": 202,
        "importance": 0.03193804368604712
    },
    "explainability": {
        "gradcam_ed": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X4A0B8B249A18FC1C_ed.png",
        "gradcam_es": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X4A0B8B249A18FC1C_es.png"
    },
    "metadata": {
        "fusion_type": "Late Fusion",
        "echo_dataset": "EchoNet-Dynamic",
        "ecg_dataset": "PTB-XL / MIT-BIH",
        "intern": "Intern 2"
    }
}

=== Cardiac-Disease-detection-using-ar-vr/INTERN-2/interim/base_scores/0X76571CA78B208B80_base.json
{
    "patient_id": "0X76571CA78B208B80",
    "prediction": {
        "base_score": 0.5190220475196838,
        "class": 0,
        "class_label": "Normal",
        "softmax": [
            0.5190220475196838,
            0.25870373845100403,
            0.22227422893047333
        ]
    },
    "echo": {
        "predicted_ef": 59.83949661254883,
        "ground_truth_ef": 64.39864489
    },
    "ecg": {
        "representation": "512-dimensional embedding",
        "top_embedding_dimension": 497,
        "importance": 3.963246344240615
    },
    "explainability": {
        "gradcam_ed": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X76571CA78B208B80_ed.png",
        "gradcam_es": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X76571CA78B208B80_es.png"
    },
    "metadata": {
        "fusion_type": "Late Fusion",
        "echo_dataset": "EchoNet-Dynamic",
        "ecg_dataset": "PTB-XL / MIT-BIH",
        "intern": "Intern 2"
    }
}
