=== Cardiac-Disease-detection-using-ar-vr/INTERN-2/schemas/base_score.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Cardiac Base Score",
  "type": "object",

  "required": [
    "patient_id",
    "prediction",
    "echo",
    "ecg",
    "explainability",
    "metadata"
  ],

  "properties": {

    "patient_id": {
      "type": "string"
    },

    "prediction": {

      "type": "object",

      "required": [
        "base_score",
        "class",
        "class_label",
        "softmax"
      ],

      "properties": {

        "base_score": {
          "type": "number"
        },

        "class": {
          "type": "integer"
        },

        "class_label": {
          "type": "string"
        },

        "softmax": {

          "type": "array",

          "items": {
            "type": "number"
          },

          "minItems":3,
          "maxItems":3
        }

      }

    },

    "echo": {

      "type":"object",

      "required":[
        "predicted_ef",
        "ground_truth_ef"
      ],

      "properties":{

        "predicted_ef":{
          "type":"number"
        },

        "ground_truth_ef":{
          "type":"number"
        }

      }

    },

    "ecg":{

      "type":"object",

      "required":[
        "representation",
        "top_embedding_dimension",
        "importance"
      ],

      "properties":{

        "representation":{
          "type":"string"
        },

        "top_embedding_dimension":{
          "type":"integer"
        },

        "importance":{
          "type":"number"
        }

      }

    },

    "explainability":{

      "type":"object",

      "required":[
        "gradcam_ed",
        "gradcam_es"
      ],

      "properties":{

        "gradcam_ed":{
          "type":"string"
        },

        "gradcam_es":{
          "type":"string"
        }

      }

    },

    "metadata":{

      "type":"object",

      "required":[
        "fusion_type",
        "echo_dataset",
        "ecg_dataset",
        "intern"
      ],

      "properties":{

        "fusion_type":{
          "type":"string"
        },

        "echo_dataset":{
          "type":"string"
        },

        "ecg_dataset":{
          "type":"string"
        },

        "intern":{
          "type":"string"
        }

      }

    }

  }

}

=== Cardiac-Disease-detection-using-ar-vr/INTERN-2/interim/base_scores/0X552F06BFE42062D8_base.json
{
    "patient_id": "0X552F06BFE42062D8",
    "prediction": {
        "base_score": 0.46147552132606506,
        "class": 0,
        "class_label": "Normal",
        "softmax": [
            0.46147552132606506,
            0.30925309658050537,
            0.2292713075876236
        ]
    },
    "echo": {
        "predicted_ef": 56.119529724121094,
        "ground_truth_ef": 64.77661769
    },
    "ecg": {
        "representation": "512-dimensional embedding",
        "top_embedding_dimension": 497,
        "importance": 3.963246344240615
    },
    "explainability": {
        "gradcam_ed": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X552F06BFE42062D8_ed.png",
        "gradcam_es": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X552F06BFE42062D8_es.png"
    },
    "metadata": {
        "fusion_type": "Late Fusion",
        "echo_dataset": "EchoNet-Dynamic",
        "ecg_dataset": "PTB-XL / MIT-BIH",
        "intern": "Intern 2"
    }
}

=== Cardiac-Disease-detection-using-ar-vr/INTERN-2/interim/base_scores/0X47EDDE2F8004F754_base.json
{
    "patient_id": "0X47EDDE2F8004F754",
    "prediction": {
        "base_score": 0.42982152104377747,
        "class": 0,
        "class_label": "Normal",
        "softmax": [
            0.42982152104377747,
            0.3385256230831146,
            0.23165296018123627
        ]
    },
    "echo": {
        "predicted_ef": 54.57941818237305,
        "ground_truth_ef": 43.38665358
    },
    "ecg": {
        "representation": "512-dimensional embedding",
        "top_embedding_dimension": 497,
        "importance": 3.963246344240615
    },
    "explainability": {
        "gradcam_ed": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X47EDDE2F8004F754_ed.png",
        "gradcam_es": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X47EDDE2F8004F754_es.png"
    },
    "metadata": {
        "fusion_type": "Late Fusion",
        "echo_dataset": "EchoNet-Dynamic",
        "ecg_dataset": "PTB-XL / MIT-BIH",
        "intern": "Intern 2"
    }
}

=== Cardiac-Disease-detection-using-ar-vr/INTERN-2/interim/base_scores/0X25D1BFBDD75BFAAE_base.json
{
    "patient_id": "0X25D1BFBDD75BFAAE",
    "prediction": {
        "base_score": 0.5230890512466431,
        "class": 0,
        "class_label": "Normal",
        "softmax": [
            0.5230890512466431,
            0.2552609145641327,
            0.22164997458457947
        ]
    },
    "echo": {
        "predicted_ef": 60.201175689697266,
        "ground_truth_ef": 68.42943083
    },
    "ecg": {
        "representation": "512-dimensional embedding",
        "top_embedding_dimension": 497,
        "importance": 3.963246344240615
    },
    "explainability": {
        "gradcam_ed": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X25D1BFBDD75BFAAE_ed.png",
        "gradcam_es": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X25D1BFBDD75BFAAE_es.png"
    },
    "metadata": {
        "fusion_type": "Late Fusion",
        "echo_dataset": "EchoNet-Dynamic",
        "ecg_dataset": "PTB-XL / MIT-BIH",
        "intern": "Intern 2"
    }
}

=== Cardiac-Disease-detection-using-ar-vr/INTERN-2/interim/base_scores/0X63CC93D7D9696690_base.json
{
    "patient_id": "0X63CC93D7D9696690",
    "prediction": {
        "base_score": 0.5273816585540771,
        "class": 0,
        "class_label": "Normal",
        "softmax": [
            0.5273816585540771,
            0.2516457140445709,
            0.22097256779670715
        ]
    },
    "echo": {
        "predicted_ef": 60.609519958496094,
        "ground_truth_ef": 64.26519735
    },
    "ecg": {
        "representation": "512-dimensional embedding",
        "top_embedding_dimension": 497,
        "importance": 3.963246344240615
    },
    "explainability": {
        "gradcam_ed": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X63CC93D7D9696690_ed.png",
        "gradcam_es": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X63CC93D7D9696690_es.png"
    },
    "metadata": {
        "fusion_type": "Late Fusion",
        "echo_dataset": "EchoNet-Dynamic",
        "ecg_dataset": "PTB-XL / MIT-BIH",
        "intern": "Intern 2"
    }
}

=== Cardiac-Disease-detection-using-ar-vr/INTERN-2/interim/base_scores/0X47847D0C76E816E7_base.json
{
    "patient_id": "0X47847D0C76E816E7",
    "prediction": {
        "base_score": 0.5126467943191528,
        "class": 0,
        "class_label": "Normal",
        "softmax": [
            0.5126467943191528,
            0.26413485407829285,
            0.22321829199790955
        ]
    },
    "echo": {
        "predicted_ef": 59.31365203857422,
        "ground_truth_ef": 61.39112147
    },
    "ecg": {
        "representation": "512-dimensional embedding",
        "top_embedding_dimension": 202,
        "importance": 0.03193804368604712
    },
    "explainability": {
        "gradcam_ed": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X47847D0C76E816E7_ed.png",
        "gradcam_es": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X47847D0C76E816E7_es.png"
    },
    "metadata": {
        "fusion_type": "Late Fusion",
        "echo_dataset": "EchoNet-Dynamic",
        "ecg_dataset": "PTB-XL / MIT-BIH",
        "intern": "Intern 2"
    }
}

=== Cardiac-Disease-detection-using-ar-vr/INTERN-2/interim/base_scores/0X4D17A70DB464D7EB_base.json
{
    "patient_id": "0X4D17A70DB464D7EB",
    "prediction": {
        "base_score": 0.4288259744644165,
        "class": 1,
        "class_label": "Mild",
        "softmax": [
            0.3383978605270386,
            0.4288259744644165,
            0.23277617990970612
        ]
    },
    "echo": {
        "predicted_ef": 50.42927551269531,
        "ground_truth_ef": 39.17780356
    },
    "ecg": {
        "representation": "512-dimensional embedding",
        "top_embedding_dimension": 497,
        "importance": 3.963246344240615
    },
    "explainability": {
        "gradcam_ed": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X4D17A70DB464D7EB_ed.png",
        "gradcam_es": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X4D17A70DB464D7EB_es.png"
    },
    "metadata": {
        "fusion_type": "Late Fusion",
        "echo_dataset": "EchoNet-Dynamic",
        "ecg_dataset": "PTB-XL / MIT-BIH",
        "intern": "Intern 2"
    }
}

=== Cardiac-Disease-detection-using-ar-vr/INTERN-2/interim/base_scores/0X7C23C2D126878C83_base.json
{
    "patient_id": "0X7C23C2D126878C83",
    "prediction": {
        "base_score": 0.5087476372718811,
        "class": 1,
        "class_label": "Mild",
        "softmax": [
            0.23702019453048706,
            0.5087476372718811,
            0.25423216819763184
        ]
    },
    "echo": {
        "predicted_ef": 41.00402069091797,
        "ground_truth_ef": 55.85548609
    },
    "ecg": {
        "representation": "512-dimensional embedding",
        "top_embedding_dimension": 497,
        "importance": 3.963246344240615
    },
    "explainability": {
        "gradcam_ed": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X7C23C2D126878C83_ed.png",
        "gradcam_es": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X7C23C2D126878C83_es.png"
    },
    "metadata": {
        "fusion_type": "Late Fusion",
        "echo_dataset": "EchoNet-Dynamic",
        "ecg_dataset": "PTB-XL / MIT-BIH",
        "intern": "Intern 2"
    }
}

=== Cardiac-Disease-detection-using-ar-vr/INTERN-2/interim/base_scores/0X1FBB4B04FD21CFFD_base.json
{
    "patient_id": "0X1FBB4B04FD21CFFD",
    "prediction": {
        "base_score": 0.493918776512146,
        "class": 0,
        "class_label": "Normal",
        "softmax": [
            0.493918776512146,
            0.2803327739238739,
            0.2257484793663025
        ]
    },
    "echo": {
        "predicted_ef": 57.98125457763672,
        "ground_truth_ef": 56.90930626
    },
    "ecg": {
        "representation": "512-dimensional embedding",
        "top_embedding_dimension": 497,
        "importance": 3.963246344240615
    },
    "explainability": {
        "gradcam_ed": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X1FBB4B04FD21CFFD_ed.png",
        "gradcam_es": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X1FBB4B04FD21CFFD_es.png"
    },
    "metadata": {
        "fusion_type": "Late Fusion",
        "echo_dataset": "EchoNet-Dynamic",
        "ecg_dataset": "PTB-XL / MIT-BIH",
        "intern": "Intern 2"
    }
}
