=== Cardiac-Disease-detection-using-ar-vr/INTERN-2/schemas/base_score.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Cardiac Base Score",
  "type": "object",

  "required": [
    "patient_id",
    "prediction",
    "echo",
    "ecg",
    "explainability",
    "metadata"
  ],

  "properties": {

    "patient_id": {
      "type": "string"
    },

    "prediction": {

      "type": "object",

      "required": [
        "base_score",
        "class",
        "class_label",
        "softmax"
      ],

      "properties": {

        "base_score": {
          "type": "number"
        },

        "class": {
          "type": "integer"
        },

        "class_label": {
          "type": "string"
        },

        "softmax": {

          "type": "array",

          "items": {
            "type": "number"
          },

          "minItems":3,
          "maxItems":3
        }

      }

    },

    "echo": {

      "type":"object",

      "required":[
        "predicted_ef",
        "ground_truth_ef"
      ],

      "properties":{

        "predicted_ef":{
          "type":"number"
        },

        "ground_truth_ef":{
          "type":"number"
        }

      }

    },

    "ecg":{

      "type":"object",

      "required":[
        "representation",
        "top_embedding_dimension",
        "importance"
      ],

      "properties":{

        "representation":{
          "type":"string"
        },

        "top_embedding_dimension":{
          "type":"integer"
        },

        "importance":{
          "type":"number"
        }

      }

    },

    "explainability":{

      "type":"object",

      "required":[
        "gradcam_ed",
        "gradcam_es"
      ],

      "properties":{

        "gradcam_ed":{
          "type":"string"
        },

        "gradcam_es":{
          "type":"string"
        }

      }

    },

    "metadata":{

      "type":"object",

      "required":[
        "fusion_type",
        "echo_dataset",
        "ecg_dataset",
        "intern"
      ],

      "properties":{

        "fusion_type":{
          "type":"string"
        },

        "echo_dataset":{
          "type":"string"
        },

        "ecg_dataset":{
          "type":"string"
        },

        "intern":{
          "type":"string"
        }

      }

    }

  }

}

=== Cardiac-Disease-detection-using-ar-vr/INTERN-2/interim/base_scores/0X3FF3AADBE6D35A09_base.json
{
    "patient_id": "0X3FF3AADBE6D35A09",
    "prediction": {
        "base_score": 0.5108196139335632,
        "class": 2,
        "class_label": "Severe",
        "softmax": [
            0.2236674278974533,
            0.2655129134654999,
            0.5108196139335632
        ]
    },
    "echo": {
        "predicted_ef": 29.983152389526367,
        "ground_truth_ef": 16.8411152
    },
    "ecg": {
        "representation": "512-dimensional embedding",
        "top_embedding_dimension": 497,
        "importance": 3.963246344240615
    },
    "explainability": {
        "gradcam_ed": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X3FF3AADBE6D35A09_ed.png",
        "gradcam_es": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X3FF3AADBE6D35A09_es.png"
    },
    "metadata": {
        "fusion_type": "Late Fusion",
        "echo_dataset": "EchoNet-Dynamic",
        "ecg_dataset": "PTB-XL / MIT-BIH",
        "intern": "Intern 2"
    }
}

=== Cardiac-Disease-detection-using-ar-vr/INTERN-2/interim/base_scores/0X482BB41895F1974D_base.json
{
    "patient_id": "0X482BB41895F1974D",
    "prediction": {
        "base_score": 0.48969221115112305,
        "class": 0,
        "class_label": "Normal",
        "softmax": [
            0.48969221115112305,
            0.2840385138988495,
            0.22626926004886627
        ]
    },
    "echo": {
        "predicted_ef": 57.71312713623047,
        "ground_truth_ef": 54.76400464
    },
    "ecg": {
        "representation": "512-dimensional embedding",
        "top_embedding_dimension": 497,
        "importance": 3.963246344240615
    },
    "explainability": {
        "gradcam_ed": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X482BB41895F1974D_ed.png",
        "gradcam_es": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X482BB41895F1974D_es.png"
    },
    "metadata": {
        "fusion_type": "Late Fusion",
        "echo_dataset": "EchoNet-Dynamic",
        "ecg_dataset": "PTB-XL / MIT-BIH",
        "intern": "Intern 2"
    }
}

=== Cardiac-Disease-detection-using-ar-vr/INTERN-2/interim/base_scores/0X2DB1613A3E1C52F3_base.json
{
    "patient_id": "0X2DB1613A3E1C52F3",
    "prediction": {
        "base_score": 0.5701806545257568,
        "class": 2,
        "class_label": "Severe",
        "softmax": [
            0.213176429271698,
            0.21664288640022278,
            0.5701806545257568
        ]
    },
    "echo": {
        "predicted_ef": 21.84794044494629,
        "ground_truth_ef": 27.65241829
    },
    "ecg": {
        "representation": "512-dimensional embedding",
        "top_embedding_dimension": 497,
        "importance": 3.963246344240615
    },
    "explainability": {
        "gradcam_ed": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X2DB1613A3E1C52F3_ed.png",
        "gradcam_es": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X2DB1613A3E1C52F3_es.png"
    },
    "metadata": {
        "fusion_type": "Late Fusion",
        "echo_dataset": "EchoNet-Dynamic",
        "ecg_dataset": "PTB-XL / MIT-BIH",
        "intern": "Intern 2"
    }
}

=== Cardiac-Disease-detection-using-ar-vr/INTERN-2/interim/base_scores/0X59A388EB10F25B7D_base.json
{
    "patient_id": "0X59A388EB10F25B7D",
    "prediction": {
        "base_score": 0.5408480763435364,
        "class": 0,
        "class_label": "Normal",
        "softmax": [
            0.5408480763435364,
            0.24042820930480957,
            0.21872374415397644
        ]
    },
    "echo": {
        "predicted_ef": 62.135528564453125,
        "ground_truth_ef": 58.06083948
    },
    "ecg": {
        "representation": "512-dimensional embedding",
        "top_embedding_dimension": 497,
        "importance": 3.963246344240615
    },
    "explainability": {
        "gradcam_ed": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X59A388EB10F25B7D_ed.png",
        "gradcam_es": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X59A388EB10F25B7D_es.png"
    },
    "metadata": {
        "fusion_type": "Late Fusion",
        "echo_dataset": "EchoNet-Dynamic",
        "ecg_dataset": "PTB-XL / MIT-BIH",
        "intern": "Intern 2"
    }
}

=== Cardiac-Disease-detection-using-ar-vr/INTERN-2/interim/base_scores/0X14F0C15097590562_base.json
{
    "patient_id": "0X14F0C15097590562",
    "prediction": {
        "base_score": 0.5519475936889648,
        "class": 0,
        "class_label": "Normal",
        "softmax": [
            0.5519475936889648,
            0.23132352530956268,
            0.2167288362979889
        ]
    },
    "echo": {
        "predicted_ef": 63.86308670043945,
        "ground_truth_ef": 61.90310698
    },
    "ecg": {
        "representation": "512-dimensional embedding",
        "top_embedding_dimension": 497,
        "importance": 3.963246344240615
    },
    "explainability": {
        "gradcam_ed": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X14F0C15097590562_ed.png",
        "gradcam_es": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X14F0C15097590562_es.png"
    },
    "metadata": {
        "fusion_type": "Late Fusion",
        "echo_dataset": "EchoNet-Dynamic",
        "ecg_dataset": "PTB-XL / MIT-BIH",
        "intern": "Intern 2"
    }
}

=== Cardiac-Disease-detection-using-ar-vr/INTERN-2/interim/base_scores/0X26B209C0083A4AD5_base.json
{
    "patient_id": "0X26B209C0083A4AD5",
    "prediction": {
        "base_score": 0.4754282832145691,
        "class": 0,
        "class_label": "Normal",
        "softmax": [
            0.4754282832145691,
            0.2966815233230591,
            0.22789014875888824
        ]
    },
    "echo": {
        "predicted_ef": 56.87113952636719,
        "ground_truth_ef": 49.75004173
    },
    "ecg": {
        "representation": "512-dimensional embedding",
        "top_embedding_dimension": 202,
        "importance": 0.03193804368604712
    },
    "explainability": {
        "gradcam_ed": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X26B209C0083A4AD5_ed.png",
        "gradcam_es": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X26B209C0083A4AD5_es.png"
    },
    "metadata": {
        "fusion_type": "Late Fusion",
        "echo_dataset": "EchoNet-Dynamic",
        "ecg_dataset": "PTB-XL / MIT-BIH",
        "intern": "Intern 2"
    }
}

=== Cardiac-Disease-detection-using-ar-vr/INTERN-2/interim/base_scores/0X558A2A6676BE7D36_base.json
{
    "patient_id": "0X558A2A6676BE7D36",
    "prediction": {
        "base_score": 0.5544294714927673,
        "class": 0,
        "class_label": "Normal",
        "softmax": [
            0.5544294714927673,
            0.229305237531662,
            0.21626530587673187
        ]
    },
    "echo": {
        "predicted_ef": 64.3504867553711,
        "ground_truth_ef": 60.78084325
    },
    "ecg": {
        "representation": "512-dimensional embedding",
        "top_embedding_dimension": 202,
        "importance": 0.03193804368604712
    },
    "explainability": {
        "gradcam_ed": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X558A2A6676BE7D36_ed.png",
        "gradcam_es": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X558A2A6676BE7D36_es.png"
    },
    "metadata": {
        "fusion_type": "Late Fusion",
        "echo_dataset": "EchoNet-Dynamic",
        "ecg_dataset": "PTB-XL / MIT-BIH",
        "intern": "Intern 2"
    }
}

=== Cardiac-Disease-detection-using-ar-vr/INTERN-2/interim/base_scores/0X79137B32737A8141_base.json
{
    "patient_id": "0X79137B32737A8141",
    "prediction": {
        "base_score": 0.5601807832717896,
        "class": 0,
        "class_label": "Normal",
        "softmax": [
            0.5601807832717896,
            0.2246527373790741,
            0.21516647934913635
        ]
    },
    "echo": {
        "predicted_ef": 65.72257995605469,
        "ground_truth_ef": 65.09822891
    },
    "ecg": {
        "representation": "512-dimensional embedding",
        "top_embedding_dimension": 202,
        "importance": 0.03193804368604712
    },
    "explainability": {
        "gradcam_ed": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X79137B32737A8141_ed.png",
        "gradcam_es": "/home/vasanth/projects/cardiac_vr_project/outputs/heatmaps/0X79137B32737A8141_es.png"
    },
    "metadata": {
        "fusion_type": "Late Fusion",
        "echo_dataset": "EchoNet-Dynamic",
        "ecg_dataset": "PTB-XL / MIT-BIH",
        "intern": "Intern 2"
    }
}
